#!/bin/bash -e

echo Installing vundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim -c 'BundleInstall'

echo Installing Command-T
cd ~/.vim/bundle/command-t/ruby/command-t
ruby extconf.rb
make
